// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtN9hz6HL5ScZG1vgiil9FQLk1efFfT7w',
    appId: '1:472828213141:web:7408e8ef1d5354d4a6a89c',
    messagingSenderId: '472828213141',
    projectId: 'ecommerceapp-d7af8',
    authDomain: 'ecommerceapp-d7af8.firebaseapp.com',
    storageBucket: 'ecommerceapp-d7af8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYwYrnHlpfg5t-5EX6zyiOwXzcKBr0Yek',
    appId: '1:472828213141:android:dcc58013f799bbbba6a89c',
    messagingSenderId: '472828213141',
    projectId: 'ecommerceapp-d7af8',
    storageBucket: 'ecommerceapp-d7af8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ2bHgRH9hA4eonxHQhjPcdqUthN5oMC0',
    appId: '1:472828213141:ios:b297161a044c8a57a6a89c',
    messagingSenderId: '472828213141',
    projectId: 'ecommerceapp-d7af8',
    storageBucket: 'ecommerceapp-d7af8.appspot.com',
    iosBundleId: 'com.example.soreAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtN9hz6HL5ScZG1vgiil9FQLk1efFfT7w',
    appId: '1:472828213141:web:04a250ba750df857a6a89c',
    messagingSenderId: '472828213141',
    projectId: 'ecommerceapp-d7af8',
    authDomain: 'ecommerceapp-d7af8.firebaseapp.com',
    storageBucket: 'ecommerceapp-d7af8.appspot.com',
  );
}
