// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBroqawypoG7fycazFndVnTD_pKeBqo7VU',
    appId: '1:518794713640:web:86a50e68acf6c34b17331d',
    messagingSenderId: '518794713640',
    projectId: 't-store-app-747b1',
    authDomain: 't-store-app-747b1.firebaseapp.com',
    storageBucket: 't-store-app-747b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCDFrHQWXeu6_a6zATby0XX80vpQZsJjA',
    appId: '1:518794713640:android:527cc3cec8dfe23e17331d',
    messagingSenderId: '518794713640',
    projectId: 't-store-app-747b1',
    storageBucket: 't-store-app-747b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPp6nkGrHE_nLDAz0121SgUSvznl7y1aQ',
    appId: '1:518794713640:ios:56938f78cbba8d8217331d',
    messagingSenderId: '518794713640',
    projectId: 't-store-app-747b1',
    storageBucket: 't-store-app-747b1.appspot.com',
    iosBundleId: 'com.example.soreAppWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBroqawypoG7fycazFndVnTD_pKeBqo7VU',
    appId: '1:518794713640:web:983689860daa8e0f17331d',
    messagingSenderId: '518794713640',
    projectId: 't-store-app-747b1',
    authDomain: 't-store-app-747b1.firebaseapp.com',
    storageBucket: 't-store-app-747b1.appspot.com',
  );

}